### ISSUE TITLE
Does not work in Lively

### ISSUE THREAD

**Issue by CrossbowDemon** [Gabrz/lively-alve#4]
Because there are no published releases, I assume that we're supposed to press "Code" and then "Download ZIP" but that .zip file cannot be opened in Lively.

**Comment by A1asd** [comment]
For anyone interested in this, i posted two solutions over on reddit:

> i just downloaded the wallpaper and tried out a few things. You could just import the `index.html` but then you have to fill in info like name, author etc. yourself. what you can do is extract the zipfile into lively's wallpaper folder (for me it was `[...]\AppData\Local\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Library\wallpapers`) then just restart lively and your wallpaper should be there :)
> 
> To customize just rightclick the wallpaper and press customize. It doesnt matter if you imported it in lively or extracted the zipfile into the wallpaper folder

just pick one of those solutions and you are good to go

**Comment by Gabrz** [comment]
@A1asd Thank you for the contribution. 

1. You can just download the zip and import the index.html with Lively, but then you loose some info about the author (me) and a new preview.gif is generated.
2. You can extract the zip to the Library\wallpapers folder (somewhere in the \AppData\Local folder). Then it keeps the author information and you have a custom preview.gif.

Both solutions work just fine.
