### ISSUE TITLE
Temperature in Fahrenheit instead of Celsius 

### ISSUE THREAD

**Issue by borgendorf** [Gabrz/lively-alve#5]
Thanks for this great wallpaper! Now that my weather API is responding, I notice that the temperature is being reported in C, but I would like to show it in F. I didn't see an option to do that, so I followed the code and edited the math statement. I'm not in a place where I can do a pull request, but here's what I changed if anyone else would like to do it, too.

lively-alve-main/assets/scripts/weather.js Line 108
`  document.getElementById("weatherTemp").innerHTML= leadingZero(Math.round(data.main.temp * (9 / 5) + 32)) + "&deg;";`

**Comment by Gabrz** [comment]
If you change the language (in the properties) to English_US the temperature should change from metric to imperial.

**Comment by borgendorf** [comment]
Oh, brilliant. Thank you! I didn't look past the default of English_World. I can see that it works (and that I need to revert my local file) because now it says 118F
